version: '3.7'

services:  
  client:
    container_name: client_container
    build: ./client
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - './client/:/app'
      - 'client_node_modules:/app/node_modules'
  
  server:
    container_name: server_container
    build: ./server
    environment:
      - IS_DEV=1
    ports:
      - "8080:8080"
    volumes:
      - ./server/:/app
    command: gunicorn server.main:app -b :8080 --worker-class aiohttp.worker.GunicornWebWorker --reload
    restart: unless-stopped
    networks:
      - app-network
  
  webserver:
    container_name: webserver_container
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - server

networks:
  app-network:
    driver: bridge

volumes:
  client_node_modules: